import { Inter } from 'next/font/google';
import './globals.css';

import { ThemeProvider } from '@/components/providers/theme-provider';
import { QueryProvider } from '@/lib/queryClient';
import { AuthProvider } from '@/lib/auth';
import { AppBackground } from '@/components/glass/app-background';
import { Toaster } from '@/components/ui/sonner';
import { TooltipProvider } from '@/components/ui/tooltip';
import { IOS_STARTUP_IMAGES } from '@/lib/ios-splash';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: {
    default: 'ManagiBot',
    template: '%s | ManagiBot',
  },
  description: 'Internal office management — attendance, leaves, announcements, and more.',
  applicationName: 'ManagiBot',
  // Stop Chrome/Google offering to "translate this page" — the UI is already English
  // and the auto-translate bar kept popping up on open and garbling the labels.
  other: { google: 'notranslate' },
  manifest: '/manifest.webmanifest',
  // iOS launch (splash) screen. Android Chrome banks on the manifest for this; iOS needs one
  // exact-size PNG per device, matched by media query — generated by scripts/gen-ios-splash.py.
  // iOS copies the image at "Add to Home Screen" time, so a change shows only after re-adding.
  appleWebApp: { capable: true, title: 'ManagiBot', statusBarStyle: 'default', startupImage: IOS_STARTUP_IMAGES },
  // App icon = ManagiBot ka nishaan, HAMESHA — public/brand/ se, code me. Settings se
  // kabhi nahi badalta (owner ka faisla: ye product ka icon hai, client ka nahi).
  // ?v pichhla cached favicon hataata hai.
  icons: {
    icon: [
      { url: '/brand/icon-512.png?v=6', sizes: '512x512', type: 'image/png' },
      { url: '/brand/icon-192.png?v=6', sizes: '192x192', type: 'image/png' },
      { url: '/brand/favicon-64.png?v=6', sizes: '64x64', type: 'image/png' },
    ],
    shortcut: ['/brand/favicon-64.png?v=6'],
    apple: [{ url: '/brand/apple-touch-icon.png?v=6', sizes: '180x180', type: 'image/png' }],
  },
};

export const viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#f7f8fc' },
    { media: '(prefers-color-scheme: dark)', color: '#0c0e16' },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" translate="no" suppressHydrationWarning>
      <body className={`${inter.variable} min-h-dvh font-sans antialiased`}>
        {/* Apply the per-device "Lite UI" choice before anything paints, so a slow
            phone never flashes the heavy glass version first. */}
        <script
          dangerouslySetInnerHTML={{
            __html: "try{if(localStorage.getItem('om_lite_ui')==='1'){document.documentElement.dataset.lite='true'}}catch(e){}",
          }}
        />
        {/* Launch screen (components/shell/launch-screen.jsx) is iOS-ONLY: Android's Chrome
            already draws a splash from the manifest, so a second logo screen there would be
            a double splash. Decided here, before first paint, the same way Lite mode is —
            `data-ios` on <html> switches the launch screen in and the plain spinner out (CSS
            in globals.css), so an iPhone never flashes the spinner first. iPadOS 13+ says
            "Macintosh" in its UA; the touch-points check catches it.
            Then, for the installed iOS app, the launch image covers the WHOLE screen but with
            statusBarStyle 'default' the web view starts below the status bar — so "44% of the
            screen" and "44% of the viewport" are different pixels and the logo would hop on
            hand-off. --ls-h/--ls-s = the real screen (iOS reports `screen` in portrait terms
            whatever the orientation), --ls-off = the bar (screen − viewport). Standalone only;
            a Safari tab keeps the plain viewport defaults. */}
        <script
          dangerouslySetInnerHTML={{
            __html: "try{var d=document.documentElement,n=navigator;if(/iPhone|iPad|iPod/.test(n.userAgent)||(n.platform==='MacIntel'&&n.maxTouchPoints>1)){d.dataset.ios='true';if(matchMedia('(display-mode: standalone)').matches||n.standalone){var p=innerWidth<=innerHeight,a=screen.width,b=screen.height,h=p?Math.max(a,b):Math.min(a,b),w=p?Math.min(a,b):Math.max(a,b),s=d.style;s.setProperty('--ls-h',h+'px');s.setProperty('--ls-s',Math.min(w,h)+'px');s.setProperty('--ls-off',Math.max(0,h-innerHeight)+'px')}}}catch(e){}",
          }}
        />
        {/* Catch the browser's install offer the instant it arrives.
            Chrome fires `beforeinstallprompt` within a moment of load, long before the
            authenticated shell mounts — the old listener lived in there, waiting on the
            /auth/me round-trip, so on a fresh device the event was simply missed. The app
            then believed it could not be installed, hid its own Install button, and sent
            people to the browser menu instead. Stashing it on `window` here means the
            React card can pick it up whenever it mounts, however late.
            IMPORTANT: this event only fires when the app is NOT already installed on THIS
            device, which makes it the most reliable per-device signal we have. */}
        <script
          dangerouslySetInnerHTML={{
            __html: "try{if('serviceWorker' in navigator){addEventListener('load',function(){navigator.serviceWorker.register('/sw.js').catch(function(){})})}}catch(e){};try{window.__omInstallEvent=null;window.__omInstalled=false;addEventListener('beforeinstallprompt',function(e){e.preventDefault();window.__omInstallEvent=e;window.__omInstalled=false;dispatchEvent(new Event('pwa-installable'))});addEventListener('appinstalled',function(){window.__omInstallEvent=null;window.__omInstalled=true;dispatchEvent(new Event('pwa-installed'))})}catch(e){}",
          }}
        />
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              <TooltipProvider>
                <AppBackground />
                {children}
                <Toaster />
              </TooltipProvider>
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
