// GENERATED by scripts/gen-ios-splash.py — haath se mat badlo, script chalao.
// iOS launch images: app/layout.jsx → metadata.appleWebApp.startupImage.
// Har entry = ek device size × orientation × light/dark; PNG ka size media query se
// EXACT match hona chahiye (device-width×dpr by device-height×dpr), warna iOS kuch nahi dikhata.
// ORDER matter karta hai: saare light pehle, saare dark baad me (aakhri match jeet-ta hai).
export const IOS_STARTUP_IMAGES = [
  // iPhone SE (1st gen)
  { url: '/brand/splash/640x1136-light.png', media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone 6s/7/8, SE (2nd/3rd gen)
  { url: '/brand/splash/750x1334-light.png', media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone 6s Plus/7 Plus/8 Plus
  { url: '/brand/splash/1242x2208-light.png', media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone X/XS/11 Pro, 12 mini, 13 mini
  { url: '/brand/splash/1125x2436-light.png', media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone XR, 11
  { url: '/brand/splash/828x1792-light.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone XS Max, 11 Pro Max
  { url: '/brand/splash/1242x2688-light.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 12/12 Pro, 13/13 Pro, 14, 16e, 17e
  { url: '/brand/splash/1170x2532-light.png', media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 12 Pro Max, 13 Pro Max, 14 Plus
  { url: '/brand/splash/1284x2778-light.png', media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 14 Pro, 15/15 Pro, 16
  { url: '/brand/splash/1179x2556-light.png', media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 14 Pro Max, 15 Plus/15 Pro Max, 16 Plus
  { url: '/brand/splash/1290x2796-light.png', media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 16 Pro, 17, 17 Pro, 18 Pro
  { url: '/brand/splash/1206x2622-light.png', media: '(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 16 Pro Max, 17 Pro Max, 18 Pro Max
  { url: '/brand/splash/1320x2868-light.png', media: '(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Air
  { url: '/brand/splash/1260x2736-light.png', media: '(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Duo (cover display) - unverified on hardware
  { url: '/brand/splash/1398x2034-light.png', media: '(device-width: 466px) and (device-height: 678px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Duo (inner display) - unverified on hardware
  { url: '/brand/splash/2007x2853-light.png', media: '(device-width: 669px) and (device-height: 951px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Duo (inner display, alt) - unverified on hardware
  { url: '/brand/splash/1878x2670-light.png', media: '(device-width: 626px) and (device-height: 890px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPad (5th/6th gen), iPad Air 2, iPad mini 4/5, iPad Pro 9.7"
  { url: '/brand/splash/1536x2048-light.png', media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad (5th/6th gen), iPad Air 2, iPad mini 4/5, iPad Pro 9.7"
  { url: '/brand/splash/2048x1536-light.png', media: '(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad mini (6th gen, A17 Pro)
  { url: '/brand/splash/1488x2266-light.png', media: '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad mini (6th gen, A17 Pro)
  { url: '/brand/splash/2266x1488-light.png', media: '(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad 10.2" (7th-9th gen)
  { url: '/brand/splash/1620x2160-light.png', media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad 10.2" (7th-9th gen)
  { url: '/brand/splash/2160x1620-light.png', media: '(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad (10th gen, A16), iPad Air (4th/5th gen), iPad Air 11" (M2/M3/M4)
  { url: '/brand/splash/1640x2360-light.png', media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad (10th gen, A16), iPad Air (4th/5th gen), iPad Air 11" (M2/M3/M4)
  { url: '/brand/splash/2360x1640-light.png', media: '(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Air (3rd gen), iPad Pro 10.5"
  { url: '/brand/splash/1668x2224-light.png', media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Air (3rd gen), iPad Pro 10.5"
  { url: '/brand/splash/2224x1668-light.png', media: '(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 11" (1st-4th gen)
  { url: '/brand/splash/1668x2388-light.png', media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 11" (1st-4th gen)
  { url: '/brand/splash/2388x1668-light.png', media: '(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 11" (M4/M5)
  { url: '/brand/splash/1668x2420-light.png', media: '(device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 11" (M4/M5)
  { url: '/brand/splash/2420x1668-light.png', media: '(device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 12.9" (all gens), iPad Air 13" (M2/M3/M4)
  { url: '/brand/splash/2048x2732-light.png', media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 12.9" (all gens), iPad Air 13" (M2/M3/M4)
  { url: '/brand/splash/2732x2048-light.png', media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 13" (M4/M5)
  { url: '/brand/splash/2064x2752-light.png', media: '(device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 13" (M4/M5)
  { url: '/brand/splash/2752x2064-light.png', media: '(device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPhone SE (1st gen)
  { url: '/brand/splash/640x1136-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone 6s/7/8, SE (2nd/3rd gen)
  { url: '/brand/splash/750x1334-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone 6s Plus/7 Plus/8 Plus
  { url: '/brand/splash/1242x2208-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone X/XS/11 Pro, 12 mini, 13 mini
  { url: '/brand/splash/1125x2436-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone XR, 11
  { url: '/brand/splash/828x1792-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPhone XS Max, 11 Pro Max
  { url: '/brand/splash/1242x2688-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 12/12 Pro, 13/13 Pro, 14, 16e, 17e
  { url: '/brand/splash/1170x2532-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 12 Pro Max, 13 Pro Max, 14 Plus
  { url: '/brand/splash/1284x2778-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 14 Pro, 15/15 Pro, 16
  { url: '/brand/splash/1179x2556-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 14 Pro Max, 15 Plus/15 Pro Max, 16 Plus
  { url: '/brand/splash/1290x2796-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 16 Pro, 17, 17 Pro, 18 Pro
  { url: '/brand/splash/1206x2622-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone 16 Pro Max, 17 Pro Max, 18 Pro Max
  { url: '/brand/splash/1320x2868-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Air
  { url: '/brand/splash/1260x2736-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Duo (cover display) - unverified on hardware
  { url: '/brand/splash/1398x2034-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 466px) and (device-height: 678px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Duo (inner display) - unverified on hardware
  { url: '/brand/splash/2007x2853-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 669px) and (device-height: 951px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPhone Duo (inner display, alt) - unverified on hardware
  { url: '/brand/splash/1878x2670-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 626px) and (device-height: 890px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  // iPad (5th/6th gen), iPad Air 2, iPad mini 4/5, iPad Pro 9.7"
  { url: '/brand/splash/1536x2048-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad (5th/6th gen), iPad Air 2, iPad mini 4/5, iPad Pro 9.7"
  { url: '/brand/splash/2048x1536-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad mini (6th gen, A17 Pro)
  { url: '/brand/splash/1488x2266-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad mini (6th gen, A17 Pro)
  { url: '/brand/splash/2266x1488-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad 10.2" (7th-9th gen)
  { url: '/brand/splash/1620x2160-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad 10.2" (7th-9th gen)
  { url: '/brand/splash/2160x1620-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad (10th gen, A16), iPad Air (4th/5th gen), iPad Air 11" (M2/M3/M4)
  { url: '/brand/splash/1640x2360-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad (10th gen, A16), iPad Air (4th/5th gen), iPad Air 11" (M2/M3/M4)
  { url: '/brand/splash/2360x1640-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Air (3rd gen), iPad Pro 10.5"
  { url: '/brand/splash/1668x2224-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Air (3rd gen), iPad Pro 10.5"
  { url: '/brand/splash/2224x1668-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 11" (1st-4th gen)
  { url: '/brand/splash/1668x2388-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 11" (1st-4th gen)
  { url: '/brand/splash/2388x1668-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 11" (M4/M5)
  { url: '/brand/splash/1668x2420-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 11" (M4/M5)
  { url: '/brand/splash/2420x1668-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1210px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 12.9" (all gens), iPad Air 13" (M2/M3/M4)
  { url: '/brand/splash/2048x2732-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 12.9" (all gens), iPad Air 13" (M2/M3/M4)
  { url: '/brand/splash/2732x2048-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
  // iPad Pro 13" (M4/M5)
  { url: '/brand/splash/2064x2752-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  // iPad Pro 13" (M4/M5)
  { url: '/brand/splash/2752x2064-dark.png', media: '(prefers-color-scheme: dark) and (device-width: 1032px) and (device-height: 1376px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)' },
];
